### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by IAfanasov** [wclr/ts-node-dev#224]
## Issue description

I can not install the last published version. I run `npm i -D ts-node-dev` and here is the output:

```
npm WARN ts-node-dev@1.0.0 requires a peer of node-notifier@* but none is installed. You must install peer dependencies yourself.
npm WARN ts-node-dev@1.0.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN ts-node@9.0.0 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path <hidden>/node_modules/ts-node-dev/lib\bin.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '<hidden>/node_modules/ts-node-dev/lib\bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!    <hidden>/.npm/_logs/2020-10-27T07_49_11_142Z-debug.log

```

## Context

*OS version (is it docker or host?), ts-node-dev version*
Host, macOS Catalina, 10.15.7

*Did you try to run with [ts-node](https://github.com/TypeStrong/ts-node)*?
NA

*Did you try to run with `--files` option enabled?*
NA

*Did you try to run with `--debug` option enabled?*
NA

*Do you have a repro example (git repo) with simple steps to reproduce your problem?*
I tried on empty folder. i run `npm init` before the installation.

**Comment by merceyz** [comment]
@whitecolor Seems the All versions released after `1.0.0-pre.65` release used Windows paths in the bin field which breaks on non-Windows machines. https://registry.yarnpkg.com/ts-node-dev/1.0.0

**Comment by mcc108** [comment]
me too

**Comment by mcc108** [comment]
@whitecolor

**Comment by mcc108** [comment]
I installed `npm` to the latest and it seems to work.

```bash
npm i - g npm
```

**Comment by tamaserdfalvi** [comment]
> I installed `npm` to the latest and it seems to work.
> 
> ```shell
> npm i -g npm
> ```

Strangely enough it fixed it for me.

**Comment by AmrAbdalrahman** [comment]
> I installed `npm` to the latest and it seems to work.
> 
> ```shell
> npm i -g npm
> ```

also fixed for me thank you

**Comment by anodynos** [comment]
Updating npm is not a great solution for docker images - could we please use https://www.npmjs.com/package/upath instead?

**Comment by merceyz** [comment]
That dependency wouldn't help as the `package.json` was published with Windows paths https://registry.yarnpkg.com/ts-node-dev/1.0.0

**Comment by whitecolor** [comment]
> That dependency wouldn't help as the package.json was published with Windows paths https://registry.yarnpkg.com/ts-node-dev/1.0.0

Hm that's, really strange, I published it with [np](https://github.com/sindresorhus/np), it should not do such crazy things.

**Comment by whitecolor** [comment]
I installed it with all PMs (yarn, npm, pnpm), on windows and linux (wsl), bin paths are alright.

I believe that something wrong with the installed npm version.

**Comment by mp3por** [comment]
Updating the npm is not a solution. Please fix. I still have it on Windows WLS 2 with npm v10.16.0

**Comment by wclr** [comment]
Should be fixed.

**Comment by aarhusgregersen** [comment]
> Should be fixed.

I'm still experiencing the issue, just tried fetching latest version of the library, even specifying it as `npm i -D ts-node-dev@1.1.3` but no luck.

Still got:
```
npm ERR! path /Users/aarhus/code/introDus/backend/node_modules/ts-node-dev/lib\bin.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/aarhus/code/introDus/backend/node_modules/ts-node-dev/lib\bin.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

There's still a windows-style backslash in the bin path, although I cannot find it in the repository, if I download it manually. 
Is there something else going on under the hood here, that may be causing issues?

**Comment by wclr** [comment]
Ok closing. It was because `np` was using lame yarn for publishing.
